In [1]:
import numpy as np

In [4]:
l=[1,2,3,4,5]
np.array(l) # converting list into array

array([1, 2, 3, 4, 5])

In [5]:
arr=np.array(l)

In [6]:
type(arr)

numpy.ndarray

In [10]:
np.array([[1,2,3],[3,4,5]]) #converting nested list into 2 dimension array..2 dimension array has 2 square brackets

array([[1, 2, 3],
       [3, 4, 5]])

In [11]:
arr1=np.array([[1,2,3],[3,4,5]])
arr1.ndim #to check dimension

2

In [12]:
arr.ndim

1

In [13]:
np.matrix(l) # matrix is always 2 dimensional...array can be one or two dimensional

matrix([[1, 2, 3, 4, 5]])

In [16]:
mat=np.matrix(l)

In [15]:
np.asanyarray(l) # cpnverting list into array

array([1, 2, 3, 4, 5])

In [17]:
np.asanyarray(mat) # matrix is already a subset of array..in python matrix is 2 dimensional array

matrix([[1, 2, 3, 4, 5]])

In [18]:
arr

array([1, 2, 3, 4, 5])

In [21]:
a=arr

In [22]:
arr[0]=100
arr

array([100,   2,   3,   4,   5])

In [23]:
a # changes in arr is reflected in a too...since both the variable pointing at same memory location

array([100,   2,   3,   4,   5])

In [24]:
b=np.copy(arr) #creates seperate memory locaation

In [25]:
b

array([100,   2,   3,   4,   5])

In [26]:
arr[1]=200

In [27]:
b # it didnt change since b is creating a replica of a in another memory location

array([100,   2,   3,   4,   5])

In [29]:
np.fromfunction(lambda i,j:i==j,(3,3)) #(3,3) is creating array with 3 columns and 3 rows,i and j are rows and column
#first is true because both are 0, second is false because either of them is 0 and otherone is 1...therefore i==j is comparinf

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [32]:
(i*i for i in range(5))

<generator object <genexpr> at 0x7f4fa0163d80>

In [33]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [34]:
iterable=list(i*i for i in range(5))

In [36]:
np.fromiter(iterable,int) #converting the iterable list into array using fromiter()

array([ 0,  1,  4,  9, 16])

In [37]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [38]:
np.fromstring('22 34 45',sep=' ') #sep is seperator...numpy gives everything in array datatype

array([22., 34., 45.])

In [40]:
np.fromstring('22,34,45',sep=',')

array([22., 34., 45.])

In [42]:
arr1

array([[1, 2, 3],
       [3, 4, 5]])

In [43]:
arr1.ndim

2

In [44]:
arr1.size # will give total no of elements inside array

6

In [45]:
arr

array([100, 200,   3,   4,   5])

In [46]:
arr.shape # 5 rows,

(5,)

In [47]:
arr1.shape # 2 rows 3 colums

(2, 3)

In [49]:
arr1.dtype # give datatype of element inside array

dtype('int64')

In [2]:
#part 2
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(0.4,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
np.arange(0.4,10.5)

array([ 0.4,  1.4,  2.4,  3.4,  4.4,  5.4,  6.4,  7.4,  8.4,  9.4, 10.4])

In [6]:
np.arange(0.4,10.5,0.2) # 0.2 is stepsize

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [8]:
list(np.arange(0.4,10.5,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [9]:
np.linspace(0,5,20) # will generate 20 data between 0 and 5

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [10]:
np.logspace(0,5,20) # will give 20 logarithmic data

array([1.00000000e+00, 1.83298071e+00, 3.35981829e+00, 6.15848211e+00,
       1.12883789e+01, 2.06913808e+01, 3.79269019e+01, 6.95192796e+01,
       1.27427499e+02, 2.33572147e+02, 4.28133240e+02, 7.84759970e+02,
       1.43844989e+03, 2.63665090e+03, 4.83293024e+03, 8.85866790e+03,
       1.62377674e+04, 2.97635144e+04, 5.45559478e+04, 1.00000000e+05])

In [11]:
np.logspace(0,5,20,base=2) 

array([ 1.        ,  1.20010272,  1.44024654,  1.72844379,  2.07431009,
        2.48938518,  2.98751792,  3.58532838,  4.30276234,  5.16375679,
        6.19703857,  7.43708284,  8.92526334, 10.71123281, 12.85457963,
       15.42681597, 18.5137638 , 22.21841828, 26.6643842 , 32.        ])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((3,4,2)) # 3 matricesof 3 dimension made of 4 rows and 2 columns

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
np.zeros((3,4,2,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
arr=np.ones((3,4))

In [22]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [23]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [24]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [25]:
np.eye(5) # 1 in diagnol

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
import pandas as pd

In [27]:
arr1=np.eye(5)

In [28]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [29]:
np.random.rand(2,3)

array([[0.3139893 , 0.53310183, 0.67398759],
       [0.35645009, 0.05479569, 0.30073534]])

In [30]:
np.random.randn(2,3)

array([[ 0.20824911, -1.00098813, -1.79497664],
       [-1.29493929,  1.88115304,  0.84359308]])

In [32]:
np.random.randint(0,10,(3,4)) #random data between 0 to 10 in 3 rows and 4 columns

array([[1, 6, 7, 7],
       [6, 7, 1, 2],
       [2, 9, 4, 7]])

In [37]:
arr2=np.random.randint(0,10,(3,4))

In [38]:
arr2

array([[6, 6, 9, 0],
       [3, 4, 2, 8],
       [9, 4, 4, 2]])

In [35]:
arr2.size

12

In [34]:
arr2.shape

(3, 4)

In [39]:
arr2.reshape(6,2) # values will not change...same values will be reshaped in different pattern

array([[6, 6],
       [9, 0],
       [3, 4],
       [2, 8],
       [9, 4],
       [4, 2]])

In [40]:
arr2.reshape(6,3) # it will require dataset of 18 howver arr2 has only 12

ValueError: cannot reshape array of size 12 into shape (6,3)

In [41]:
arr2.reshape(2,6)

array([[6, 6, 9, 0, 3, 4],
       [2, 8, 9, 4, 4, 2]])

In [42]:
arr2.reshape(4,3)

array([[6, 6, 9],
       [0, 3, 4],
       [2, 8, 9],
       [4, 4, 2]])

In [43]:
arr2.reshape(4,-1)

array([[6, 6, 9],
       [0, 3, 4],
       [2, 8, 9],
       [4, 4, 2]])

In [44]:
arr2.reshape(2,2,3)# same data set can be reshaped into 3d dataset

array([[[6, 6, 9],
        [0, 3, 4]],

       [[2, 8, 9],
        [4, 4, 2]]])

In [45]:
arr3=np.random.randint(1,10,(5,6))

In [46]:
arr3

array([[1, 9, 9, 6, 9, 6],
       [9, 8, 3, 2, 2, 9],
       [6, 7, 7, 2, 4, 1],
       [7, 7, 7, 7, 7, 6],
       [9, 1, 9, 6, 9, 2]])

In [48]:
arr3>8

array([[False,  True,  True, False,  True, False],
       [ True, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True, False,  True, False,  True, False]])

In [49]:
arr3[arr3>8] # will give only dataset greater than 8

array([9, 9, 9, 9, 9, 9, 9, 9])

In [50]:
arr3[0] #will give row 0

array([1, 9, 9, 6, 9, 6])

In [51]:
arr3[0,[0,1]] #exctract first 2 data

array([1, 9])

In [54]:
arr3[2:4,[2,3]] #2:4 2nd to 4th row and[2,3] is 2nd and 3rd column

array([[7, 2],
       [7, 7]])

In [60]:
arr4=np.random.randint(1,3,(3,3))

In [57]:
arr4

array([[1, 1, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [59]:
arr5=np.random.randint(1,3,(3,3))

In [61]:
arr5

array([[1, 1, 1],
       [2, 2, 1],
       [2, 1, 1]])

In [62]:
arr4+arr5

array([[3, 2, 3],
       [4, 4, 2],
       [4, 2, 3]])

In [63]:
arr4*arr5 #multiplies values and not matrix multiplication

array([[2, 1, 2],
       [4, 4, 1],
       [4, 1, 2]])

In [64]:
#matrix multiplication
arr4@arr5

array([[8, 6, 5],
       [8, 7, 5],
       [8, 6, 5]])

In [74]:
#numpy broadcasting
arr6=np.zeros((3,4))

In [75]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
arr6+5 #this is broadcasting

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [79]:
a=np.array([1,2,3,4])

In [80]:
arr6+a # since all values in arr6 are 0..it adds the values row wise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [81]:
b=np.array([2,3,4])# to add values column wise

In [82]:
arr6+b # will show error.therefore need to rotate the array to perform operation row wise

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [83]:
b=np.array([[2,3,4]])

In [86]:
b.T

array([[2],
       [3],
       [4]])

In [85]:
arr6+b.T

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [93]:
arr7=arr6+b.T

In [94]:
np.sqrt(arr7) #square root

array([[1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ]])

In [95]:
np.log10(arr7)

array([[0.30103   , 0.30103   , 0.30103   , 0.30103   ],
       [0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999]])

In [96]:
np.exp(arr7)

array([[ 7.3890561 ,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [20.08553692, 20.08553692, 20.08553692, 20.08553692],
       [54.59815003, 54.59815003, 54.59815003, 54.59815003]])

In [97]:
np.min(arr7)

2.0

In [1]:
#part 3
import numpy as np

In [3]:
# array manipulation
arr8=np.random.randint(1,10,(4,4))

In [4]:
arr8.reshape(8,2)

array([[9, 1],
       [4, 8],
       [4, 4],
       [9, 4],
       [1, 1],
       [2, 4],
       [4, 9],
       [8, 3]])

In [5]:
arr8.T

array([[9, 4, 1, 4],
       [1, 4, 1, 9],
       [4, 9, 2, 8],
       [8, 4, 4, 3]])

In [7]:
arr8.flatten()

array([9, 1, 4, 8, 4, 4, 9, 4, 1, 1, 2, 4, 4, 9, 8, 3])

In [10]:
arr8

array([[9, 1, 4, 8],
       [4, 4, 9, 4],
       [1, 1, 2, 4],
       [4, 9, 8, 3]])

In [9]:
np.expand_dims(arr8,axis=1) # will expand dimension

array([[[9, 1, 4, 8]],

       [[4, 4, 9, 4]],

       [[1, 1, 2, 4]],

       [[4, 9, 8, 3]]])

In [11]:
np.expand_dims(arr8,axis=0)

array([[[9, 1, 4, 8],
        [4, 4, 9, 4],
        [1, 1, 2, 4],
        [4, 9, 8, 3]]])

In [12]:
data=np.array([[1],[2],[3]]) 

In [13]:
np.squeeze(data)# will reduce dimension 

array([1, 2, 3])

In [15]:
np.repeat(data,2) # will repeat data twice

array([1, 1, 2, 2, 3, 3])

In [16]:
np.repeat(data,4) 

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [20]:
np.roll(data,1) # rolls or rotates data

array([[3],
       [1],
       [2]])

In [18]:
np.roll(data,2) 

array([[2],
       [3],
       [1]])

In [21]:
np.roll(data,3) 

array([[1],
       [2],
       [3]])

In [22]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
# binary operations
arr9=np.random.randint(1,10,(3,4))
arr10=np.random.randint(1,10,(3,4))

In [25]:
arr9

array([[1, 3, 2, 7],
       [9, 8, 3, 4],
       [9, 4, 7, 9]])

In [26]:
arr10

array([[3, 6, 6, 2],
       [6, 5, 3, 8],
       [5, 5, 9, 5]])

In [27]:
arr9+arr10

array([[ 4,  9,  8,  9],
       [15, 13,  6, 12],
       [14,  9, 16, 14]])

In [28]:
arr9*arr10

array([[ 3, 18, 12, 14],
       [54, 40,  9, 32],
       [45, 20, 63, 45]])

In [29]:
arr9**arr10

array([[       1,      729,       64,       49],
       [  531441,    32768,       27,    65536],
       [   59049,     1024, 40353607,    59049]])

In [30]:
-arr9

array([[-1, -3, -2, -7],
       [-9, -8, -3, -4],
       [-9, -4, -7, -9]])

In [31]:
arr9>arr10

array([[False, False, False,  True],
       [ True,  True, False, False],
       [ True, False, False,  True]])

In [37]:
# string functions
arr11=np.array(['nik','hil','bhanu','shali'])

In [38]:
arr11

array(['nik', 'hil', 'bhanu', 'shali'], dtype='<U5')

In [39]:
np.char.upper(arr11) # string functions are within char class

array(['NIK', 'HIL', 'BHANU', 'SHALI'], dtype='<U5')

In [40]:
np.char.capitalize(arr11) # capitalise first alphabet

array(['Nik', 'Hil', 'Bhanu', 'Shali'], dtype='<U5')

In [41]:
np.char.title(arr11) # capitalise first alphabet too

array(['Nik', 'Hil', 'Bhanu', 'Shali'], dtype='<U5')

In [42]:
#mathematical functions
arr10

array([[3, 6, 6, 2],
       [6, 5, 3, 8],
       [5, 5, 9, 5]])

In [43]:
np.sin(arr10) # sin values

array([[ 0.14112001, -0.2794155 , -0.2794155 ,  0.90929743],
       [-0.2794155 , -0.95892427,  0.14112001,  0.98935825],
       [-0.95892427, -0.95892427,  0.41211849, -0.95892427]])

In [44]:
np.cos(arr10)

array([[-0.9899925 ,  0.96017029,  0.96017029, -0.41614684],
       [ 0.96017029,  0.28366219, -0.9899925 , -0.14550003],
       [ 0.28366219,  0.28366219, -0.91113026,  0.28366219]])

In [45]:
np.tan(arr10)

array([[-0.14254654, -0.29100619, -0.29100619, -2.18503986],
       [-0.29100619, -3.38051501, -0.14254654, -6.79971146],
       [-3.38051501, -3.38051501, -0.45231566, -3.38051501]])

In [46]:
np.log10(arr10)

array([[0.47712125, 0.77815125, 0.77815125, 0.30103   ],
       [0.77815125, 0.69897   , 0.47712125, 0.90308999],
       [0.69897   , 0.69897   , 0.95424251, 0.69897   ]])

In [47]:
np.exp(arr10)

array([[2.00855369e+01, 4.03428793e+02, 4.03428793e+02, 7.38905610e+00],
       [4.03428793e+02, 1.48413159e+02, 2.00855369e+01, 2.98095799e+03],
       [1.48413159e+02, 1.48413159e+02, 8.10308393e+03, 1.48413159e+02]])

In [48]:
np.power(arr10,2) # power 2 willcalculate square

array([[ 9, 36, 36,  4],
       [36, 25,  9, 64],
       [25, 25, 81, 25]])

In [49]:
np.mean(arr10)

5.25

In [50]:
np.median(arr10)

5.0

In [51]:
np.std(arr10)# standard deviation

1.920286436967152

In [52]:
np.var(arr10) # variance

3.6875

In [53]:
np.min(arr10)

2

In [54]:
np.max(arr10)

9

In [56]:
# arithmatic operation
arr9

array([[1, 3, 2, 7],
       [9, 8, 3, 4],
       [9, 4, 7, 9]])

In [57]:
arr10

array([[3, 6, 6, 2],
       [6, 5, 3, 8],
       [5, 5, 9, 5]])

In [59]:
arr9-arr10

array([[-2, -3, -4,  5],
       [ 3,  3,  0, -4],
       [ 4, -1, -2,  4]])

In [62]:
np.subtract(arr9,arr10) # will perform same function

array([[-2, -3, -4,  5],
       [ 3,  3,  0, -4],
       [ 4, -1, -2,  4]])

In [63]:
np.multiply(arr9,arr10)

array([[ 3, 18, 12, 14],
       [54, 40,  9, 32],
       [45, 20, 63, 45]])

In [64]:
np.mod(arr9,arr10) # will give remainder

array([[1, 3, 2, 1],
       [3, 3, 0, 4],
       [4, 4, 7, 4]])

In [65]:
np.power(arr9,arr10)

array([[       1,      729,       64,       49],
       [  531441,    32768,       27,    65536],
       [   59049,     1024, 40353607,    59049]])

In [66]:
np.sqrt(arr9)

array([[1.        , 1.73205081, 1.41421356, 2.64575131],
       [3.        , 2.82842712, 1.73205081, 2.        ],
       [3.        , 2.        , 2.64575131, 3.        ]])

In [67]:
#statistical function
np.mean(arr9)

5.5

In [7]:
#part 4
#sort,search and counting functions
import numpy as np
arr12=np.array([12,14,3,5,16])

In [8]:
np.sort(arr12)

array([ 3,  5, 12, 14, 16])

In [10]:
np.searchsorted(arr12,6) #gives the index where element is to be inserted to maintain order

4

In [13]:
arr13=np.array([324,454,54,67,90,9,76,5,0])

In [14]:
np.count_nonzero(arr13)

8

In [21]:
np.where(arr13>0) # gives index position where data is greater than 0

(array([0, 1, 2, 3, 4, 5, 6, 7]),)

In [19]:
np.extract(arr13 > 50,arr13)

array([324, 454,  54,  67,  90,  76])

In [20]:
# byte swapping
arr13

array([324, 454,  54,  67,  90,   9,  76,   5,   0])

In [22]:
arr13.byteswap()

array([ 4900197869555810304, -4179058979223109632,  3891110078048108544,
        4827858800541171712,  6485183463413514240,   648518346341351424,
        5476377146882523136,   360287970189639680,                    0])

In [23]:
#copy and views
a=np.copy(arr13) # create deep copy ie create seperate memory location with variable a

In [26]:
a[0]=234

In [27]:
a

array([234, 454,  54,  67,  90,   9,  76,   5,   0])

In [28]:
arr13

array([324, 454,  54,  67,  90,   9,  76,   5,   0])

In [24]:
b=arr13.view() # doesnt create deep copy...creates variable pointing to same memory location

In [25]:
b

array([324, 454,  54,  67,  90,   9,  76,   5,   0])

In [29]:
b[0]=500

In [30]:
b

array([500, 454,  54,  67,  90,   9,  76,   5,   0])

In [31]:
arr13

array([500, 454,  54,  67,  90,   9,  76,   5,   0])

In [32]:
# matrix library
import numpy.matlib as nm

In [33]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [35]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [37]:
# linear algebra

In [38]:
arr14=np.random.randint([[2,3],[4,5]])

In [39]:
arr15=np.random.randint([[5,3],[2,5]])

In [40]:
arr14

array([[0, 2],
       [3, 4]])

In [41]:
arr15

array([[0, 2],
       [1, 3]])

In [42]:
np.dot(arr14,arr15)

array([[ 2,  6],
       [ 4, 18]])

In [43]:
arr14@arr15 #same result....ie matrix multiplication

array([[ 2,  6],
       [ 4, 18]])