In [ ]:
'''import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.'''

In [6]:
import numpy as np
list= [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(list)

In [7]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [14]:
type(array_list)

numpy.ndarray

In [13]:
type(list)

list

In [ ]:
'''Yes, there is a difference in the data type of the variables list_ and array_list.

The variable list_ is a Python list, which can hold elements of different data types. In this case, the elements of list_ are strings.

The variable array_list is a NumPy array, created using the np.array() function. NumPy arrays are homogeneous, meaning they can only contain elements of the same data type. In this case, since the elements of list_ are strings, the elements of array_list will also be treated as strings.'''

In [15]:
'''Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.# Print data types of elements in list_'''
print("Data types of elements in list_:")
for element in list:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
'''Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.'''

In [16]:
array_list = np.array(object = list, dtype = int) #yes there qill be difference..this will convert string dtype of elements of list into int in array

In [17]:
print("Data types of elements in list_:")
for element in list:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [18]:
'''Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size'''
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [19]:
num_array.shape

(2, 3)

In [20]:
num_array.size

6

In [21]:
'''Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]'''
import numpy as np

array_zeros = np.zeros((3, 3))

print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
'''Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]'''

identity_matrix = np.eye(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
